### ISSUE TITLE
Tratamento de exceções

### ISSUE THREAD

**Issue by oliveiralex** [brunosoaresbomfim/dsclients#1]
Olá Bruno, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

O Trabalho foi aceito, parabéns! Porém, faltou fazer o tratamento de exceções. Está retornando erro 500 quando é informado um id que não existe. Tanto para buscar cliente pelo id, update e delete.

**Observação:** Além disso, quando eu executei o seu projeto, os dados do arquivo import.sql não foram inseridos corretamente no banco h2. Precisei de ajustar o nome do arquivo para data.sql para executar corretamente.

Abraço e bons estudos

**Comment by brunosoaresbomfim** [comment]
Olá, boa tarde, estou bem e você? Pronto, já vou corrigir esse problemas,
acabei fazendo no meu notebook e acredito que não subi essas alterações no
github.

Em seg., 17 de mai. de 2021 às 15:08, Alexandre ***@***.***>
escreveu:

**Comment by oliveiralex** [comment]
Olá Bruno,
A correção foi realizada com sucesso! Parabéns
Abraço
